### ISSUE TITLE
submit_github_binary.py throws no module named pkg_resources.extern found

### ISSUE THREAD

**Issue by HammerPavel** [ungoogled-software/ungoogled-chromium-binaries#144]
utilities/submit_github_binary.py -h / --help, as well as all the other /utilities scripts also result in ModuleNotFoundError.
locally cloned the repo just a couple of days ago. worked before on the same machine. all packages from requirements.txt are present and i did pacman -S them again.
i did however generate the ini file manually and pull request then

--------------------------------------------------------------------------------------------------------------
comment as of yesterday:
i just edited the html manually, its all in my repo and i'm dead out of time for today i need to leave. if someone can just manually pull from my repo that'd be greatly appreciated

**Comment by Eloston** [comment]
Hmm you shouldn't need pkg_resources for `submit_github_binaries`; that's just some sloppy coding on my part. I'll fix that.

BTW `requirements.txt` is for pip, not for distro-provided packages. Perhaps the distro-provided packages you installed don't include `pkg_resources`.
