### ISSUE TITLE
Discussion for the initial webpage design

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-binaries#2]
Discussion for designing the downloads page.

EDIT: Should mention that a simple webpage is already up.

@9Morello, what do you think?

**Comment by 9Morello** [comment]
@Eloston We will have to think about it. What page do you expect the user to come across first: ug's main repository, or the webpage we're creating? If its the first, then I think the current design is good enough. Just make it more pretty with a Chromium and/or distro logos and it should be good to go.

If its the second, I think its a good idea to design around putting [some info from the README](https://github.com/Eloston/ungoogled-chromium) there. The [tox.chat](https://tox.chat/index.html) page is a good inspiration, imo - clean and clear enough, providing useful information on privacy and how to download it.

**Comment by Eloston** [comment]
This webpage will just be for downloads, because it's something I'm going to allow others to have more control over. The main repository's control is going to stay the same.

I would like to hear more about how you'll like to separate the OSes more. I designed the page the way it is now because I knew it would be easy to autogenerate, but I don't want it to be too confusing to users.

**Comment by 9Morello** [comment]
I think its a good idea to place them in different parts of the screen, according to platform. Maybe a 3-way layout with Windows, Linux and OS X. And have visual indication of the platform. Maybe something like [this](https://tox.chat/download.html), but changing the Linux part so the user doesn't download the wrong binaries. I'll see if I can mock up something when I have time.

BTW, I'm going to build new binaries for OS X now, is it a good idea to place Google Chrome's Widevine plugin on them?

**Comment by Eloston** [comment]
Oh ok that layout looks nice.

Regarding Widevine, you shouldn't place those binaries in them because I want users to have an option to use a binary built completely from source (as possible).

**Comment by 9Morello** [comment]
Ok. I will upload the new `.dmg` soon.
It seems a new subversion of 55 was released.

**Comment by 9Morello** [comment]
@Eloston I built a 55.0.2883.95 package. Should I just upload it or wait for the master branch to be updated?

**Comment by Eloston** [comment]
You're free to add and update binaries on the downloads page as you wish. I'm not as strict on what happens to this repository as the main one.

**Comment by 9Morello** [comment]
@Eloston Thanks, I'll upload it right now.
Could you elaborate a bit about how `github_release_helper.py` works?

**Comment by Eloston** [comment]
Pass in `--help` and it will tell you what arguments it takes. Basically it spits out markdown (to stdout, so you should probably redirect output to a file) with the correct download URL and hashes for the files you input.

I used it when I made releases on the main repository, so it has some additional features that are too useful here (although I did modify it so the download URLs would be correct for uploading to the releases page on this repository)

Here's an example of some arguments you can use: `55.0.2883.87-1 -- "Windows 32-bit" path/to/buildzip`. Probably easier to see for yourself than for me to describe it here.

**Comment by 9Morello** [comment]
Oh, this is pretty convenient. Nice script.

**Comment by Eloston** [comment]
Thanks. You can modify it as you see fit.

**Comment by Eloston** [comment]
Closing this now, since an initial design has been done already. A rewrite of the website is being done as we speak. Come on Gitter to discuss this more.
