### ISSUE TITLE
There should be more Windows releases.

### ISSUE THREAD

**Issue by tasty0tomato** [ungoogled-software/ungoogled-chromium-binaries#227]
Such as 87.0.8280.88, there isn't its own source code but also can be compiled by 87.0.8280.67 windows  patchs and 87.0.8280.88 code.

I have tried yesterday and it worked.

**Comment by tangalbert919** [comment]
Don't worry. I am pushing Windows releases as quickly as I possibly can.

**Comment by tasty0tomato** [comment]
Thanks a lot!!!
