### ISSUE TITLE
Compilation process - multi-target simplified compilation

### ISSUE THREAD

**Issue by mdedonno1337** [ungoogled-software/ungoogled-chromium-binaries#248]
Hi,

Base upon the number of PR today (#244, #245, #246 and #247), I think that we could centralize a bit more the compilation of the binaries, hence reduce the load and sparce work.

In particular, we could compile the portable (#244), appimage (#245) and probably the deb versions at once in a docker image.
I suspect that the compilation for the others plateforms (except mac, android and windows) could be done this way.

I did not check the compilation process for each of the targets, but I suspect that part of the build is common between some of the targets (at least the portable, appimage and deb), hence wastefull to make the compilation by mutilple people.

I'm working on a repo to make the compilation for some targets and make the PR in this repo "automatically" (done manually at the moment, may be pushed to a CICD later one, I dont know).

What do you think, @Eloston ?

**Comment by Eloston** [comment]
I think it's a decent idea for Portable Linux. With a build artifact of standard Portable Linux, you could repackage it into AppImage and Snap formats. Off the top of my head, don't think there's any other currently maintained formats that use Portable Linux as a base.
