### ISSUE TITLE
FR: Make possible to publish/download more binaries for same version, but from different authors

### ISSUE THREAD

**Issue by ian-moone** [ungoogled-software/ungoogled-chromium-binaries#28]
I'm not sure if it is already possible, but it seems that for each version released, it's only possible to publish a binary made by one author? If that's so, then as the title says... It will be nice to have an option for different binaries, built on different environments.

I myself would like to publish signed portable binaries built on my Gentoo box. One use case, at least, will be for my _ebuild overlay_, which I maintain both, source and binary based ebuilds, this would remove the waiting time for someone to release a binary version.

Off course, I could publish my own binaries somewhere else, recluse from the official repo, but that wouldn't benefit other users.

**Comment by intika** [comment]
Indeed current site system does not list different users for different release it's kind a who publish first...  
There is many possible solutions but they all require changing the site script generator  (site_generator.py) and the ini version nomenclature to something like "69.0.3497.100-2-Publisher.ini"

**Or** Keep the main table with versions only published by @Eloston and add an other table per publisher we would then have the name of the publisher in an ini file that list its different published version

**Or** Simpler keep first the first table with version only by @Eloston and the second table would list publisher + current released version + link to their fork 

many possible solution it's up to @Eloston but yeah it's a nice idea

**Comment by Eloston** [comment]
Let me give some context:

* The point of each config bundle is to capture different kinds of binaries that can result from a combination of GN flags, patches, domain substitution, and binary pruning.
* Each "platform" in ungoogled-chromium-binaries is a combination of a packaging type and a config bundle. Every "platform" is supposed to target a group of OS configurations, which is basically the "environment" concept you are referring to.
    * e.g. Debian stretch amd64 binaries target all Debian stretch amd64 computers.
* One important property of "platforms" is that the binaries for a given "platform" are supposed to be the same, no matter who builds them.
    * This doesn't necessarily satisfy reproducibility (yet), but all builds should at least have the same runtime requirements and behaviors, such as shared object dependencies, runtime performance, and functionality of features.

Now, Portable Linux is unique in that it is supposed to target **all Linux distributions**. Thus, having a Portable Linux binary targeting *a specific environment* makes no sense.

If a Portable Linux build made on one distribution *cannot* be run on another, then this is a bug in Portable Linux. Please open an issue in ungoogled-chromium for this scenario.

In the event that Portable Linux cannot be made distribution-agnostic, then we will need to limit the target of Portable Linux builds to be the distribution it was built on, and add more ungoogled-chromium-binaries "platforms". (Also, if the distro cannot be universally auto-detected within `linux_simple`, we would need to add more packaging types to insert info about the distros the binaries were built on into the tar package.)

**Comment by intika** [comment]
The only difference i can see with different builds of portable version is "against what glibc version the package was built" ... in my case i needed it to be as low as v2.22 (ldd --version) my main system still did not updated stable package... as the build is done against a reasonable version then more system should be compatible... i still did not see issues about glibc version so with "max 2.22" i think we are good to go for portable release. for now
