### ISSUE TITLE
Why not use Travis / AppVeyor / something else for the building?

### ISSUE THREAD

**Issue by devnoname120** [ungoogled-software/ungoogled-chromium-binaries#30]
Having releases from random people is a security risk.

You could ask these providers to increase the compile time limit for your project. We use Travis for [vitasdk](https://github.com/vitasdk) and they agreed to increase the limit for us.

**Comment by Eloston** [comment]
> Having releases from random people is a security risk.

Yes. In fact, there's a important notice about this on the frontpage of the download site and the README of ungoogled-chromium.

> You could ask these providers to increase the compile time limit for your project. 

Interesting, but I don't think it's reasonable to ask these services to make CI builds that take ~3-4 hours, 8 GB of RAM or more, and 10 GB of storage or more. What are your build requirements like? Is compile time the only thing you needed to worry about?

**Comment by devnoname120** [comment]
Indeed compile time was our only issue, we didn't have RAM or storage issues.

**Comment by Eloston** [comment]
If you encounter a viable method, please let us know in the ungoogled-chromium repo. Thanks.
