### ISSUE TITLE
102.0.5005.115-1 doesn't run in Ubuntu Mate 20.04.4

### ISSUE THREAD

**Issue by brunoalvieira** [ungoogled-software/ungoogled-chromium-binaries#308]
/tmp/.mount_ungoogof1SWd/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_ungoogof1SWd/opt/google/chrome/chrome)
/tmp/.mount_ungoogof1SWd/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_ungoogof1SWd/opt/google/chrome/chrome)
/tmp/.mount_ungoogof1SWd/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_ungoogof1SWd/opt/google/chrome/chrome)
/tmp/.mount_ungoogof1SWd/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_ungoogof1SWd/opt/google/chrome/chrome)

apt-cache policy libc6
libc6:
  Instalado: 2.31-0ubuntu9.9
  Candidato: 2.31-0ubuntu9.9
  Tabela de versão:
 *** 2.31-0ubuntu9.9 500
        500 http://br.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.31-0ubuntu9.7 500
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     2.31-0ubuntu9 500
        500 http://br.archive.ubuntu.com/ubuntu focal/main amd64 Packages

ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
Este é um software livre; leia os fontes para condições de cópia. NÃO HÁ
QUALQUER GARANTIA; nem para COMERCIALIZAÇÃO ou ADEQUAÇÃO A QUALQUER
PROPÓSITO EME PARTICULAR.
Escrito por Roland McGrath e Ulrich Drepper.

**Comment by FranBar1966** [comment]
Same in Debian 5.10

**Comment by frank-github** [comment]
same here and with latest appImage too :-(

ungoogled-chromium_103.0.5060.53-1.1.AppImage

Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

**Comment by clickot** [comment]
i switched back to a debian based builder image which seems to fix this problem, see https://github.com/ungoogled-software/ungoogled-chromium/issues/2001. As soon the PR for the officiel binaries website containing the new links is merged they can be downloaded from there. Until that you may get them here: https://github.com/clickot/ungoogled-chromium-binaries/releases

**Comment by brunoalvieira** [comment]
It runs now.

Thank you for attention.

**Comment by clickot** [comment]
@brunoalvieira Great! Could you please close this issue then?
