### ISSUE TITLE
Add 102.0.5005.148(or 134) BINARIES For PorTable Linux

### ISSUE THREAD

**Issue by PreTexTaTo** [ungoogled-software/ungoogled-chromium-binaries#353]
YoU See... THe 102.0.5005.115-1 BINARIES For PorTable Linux iS Corrupted.
THe Same problem HappeNs WiTH 102.0.5005.115-1 AppiMage For Linux.
So, Please... Build and Release ANOTHER Version oF 102 CHroMiUm Series.
THANKFUL!

**Comment by PreTexTaTo** [comment]
THis WHaT Happens WHen I ExecuTe THe BINARY File.

**./chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./chrome)**

ALL oTHers ungloogle-chromium releases works Fine! I TesTEd... 090, 099, 103, 104 ,105 and 107.
(Some MiNor Problems WiTH THe New Ones, buT because i Am using and oUTdaTed Linux i THiNK).

THis issue ONLY Happens WiTH THis 102.0.5005.115-1 Release.

Linux 5.15.0-50-generic #56~20.04.4-Ubuntu SMP Tue Sep 27 15:51:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by PreTexTaTo** [comment]
oH! I AlmosT ForgoT To SaY...
THis 102 Release does NoT Run.
All oTHers Releases i TesTed Run(THe NeW Ones WiTH SoMe Messages).

**Comment by networkException** [comment]
we dont provide support for outdated versions.
