### ISSUE TITLE
70.0.3538.110-2 not working (macos)

### ISSUE THREAD

**Issue by zeptoSteve** [ungoogled-software/ungoogled-chromium-binaries#39]
this is the release from @kramred, I downloaded it like 3 times. moved from the disk image, left on the disk image, it just doesn't work. the previous release from the same user works fine (70.0.3538.110-1).

EDIT: macOS 10.14.1.

**Comment by zeptoSteve** [comment]
further details:

![screen shot 2018-12-01 at 3 19 53 pm](https://user-images.githubusercontent.com/7691233/49333863-33e9ff80-f58c-11e8-8067-f9636847f59f.png)

**Comment by kramred** [comment]
Re-downloaded the disk image and it work for me (macOS 10.12.6). Did you check the hashes (MD5, SHA1)?  
Alternatively, try downloading from the terminal with curl:
`curl -JOL https://github.com/kramred/ungoogled-chromium-binaries/releases/download/70.0.3538.110-2/ungoogled-chromium_70.0.3538.110-2_macos.dmg && md5 ungoogled-chromium_70.0.3538.110-2_macos.dmg`

**Comment by zeptoSteve** [comment]
Re-downloaded from this page: "https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/macos/70.0.3538.110-2" and from "https://github.com/kramred/ungoogled-chromium-binaries/releases"

I checked all three hashed (using `md5`, `gsha1sum`, `gsha256sum`) and they all matched. Still got the error, though.

**Comment by zeptoSteve** [comment]
I can't imagine why it didn't work the first time, but now it works. Sorry for the false alarm.
