### ISSUE TITLE
Atom feed not updated?

### ISSUE THREAD

**Issue by waldner** [ungoogled-software/ungoogled-chromium-binaries#524]
It seems the atom feed isn't being updated with the latest relases. For example, the latest Linux Appimage version is [123.0.6312.105-1](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/appimage/64bit/123.0.6312.105-1) but the feed still lists 121.0.6167.160-1 as latest.

**Comment by networkException** [comment]
The feed changed to https://ungoogled-software.github.io/ungoogled-chromium-binaries/feed.xml

**Comment by waldner** [comment]
Thanks. Perhaps it's worth updating the link in the README then, and the one in the binaries page, as they all still point to the old one.

**Comment by networkException** [comment]
ah I see, forgot some places
