### ISSUE TITLE
Create a current tag release for Arch Linux

### ISSUE THREAD

**Issue by Tank-Missile** [ungoogled-software/ungoogled-chromium-binaries#62]
This will allow easy updating of arch binaries by simply placing the following into /etc/pacman.conf:
```
[ungoogled-chromium]
Server = https://github.com/ungoogled-software/ungoogled-chromium-binaries/releases/tag/current
```
Four database files are needed as well, which can be generated with the use of the repo-add command. More information [here](https://fusion809.github.io/how-to-create-archlinux-repository/#toc12).

**Comment by Eloston** [comment]
What are the advantages of using this over the AUR?

**Comment by Tank-Missile** [comment]
The AUR requires manual use of makepkg unless using an AUR helper, which not all users of arch prefer using. Also, with the current setup of ungoogled-chromium-bin, it requires 3 different things to occur at once before the package can be installed: someone has to make a pull request for an updated binary, then you have to accept it. Then whoever manages the AUR package has to update the binary by using their own PKGBUILD. I don't believe they can just link it to the pkg.tar.xz file directly. Since the binaries would be hosted on GitHub still, it doesn't add extra burden to you I think.

**Comment by v00v** [comment]
I vote for this too :-) I think it would be a great idea.

**Comment by Tank-Missile** [comment]
Any updates on this?

**Comment by Eloston** [comment]
If someone wants to look into this, that's fine by me. But I would like to call the tag `archlinux-current` or something to know it's specifically for Arch Linux. Also, would be worth investigating if it should be a separate branch or repo since this repo just contains the website files.

**Comment by Tank-Missile** [comment]
So from looking at the website files, what you do is simply make links to binaries hosted on forked repositories? In that case, you wouldn't host anything yourself besides the database files that pacman needs to authenticate the pkg. A single link should be used to get the latest pkg. How it's done right now, each release is given a separate link. Perhaps archlinux-current could somehow link to the binary being hosted on their account? Every time there's an update, just have it point to the new binary, rather than hosting it on your account. I'm sure there's a sane solution that has both convenience and security.

**Comment by Eloston** [comment]
It is possible to configure CI on this repo so that it can copy the binary over to a new branch and update the tag. Would take some time to setup though.

**Comment by Msouza91** [comment]
@Eloston What are the files needed to configure this? I'm no expert but I think that I could help set this up maybe... The compiling process is too finicky and long, we need a more sane and fast way to install and update.

**Comment by Eloston** [comment]
Well this issue is a bit old. I don't think we're going to do this because of https://github.com/Eloston/ungoogled-chromium/issues/1023 or https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/70.

We can revisit this issue if those doesn't work out. For now, closing as wontfix.
