### ISSUE TITLE
are the builds on chromium.woolyss.com trustable, and why aren't they submitted here too?

### ISSUE THREAD

**Issue by okay** [ungoogled-software/ungoogled-chromium-binaries#73]
i recently came across https://chromium.woolyss.com, which provides downloads to chromium binaries. it seems here there are some "ungoogled" versions provided, compiled by "marmaduke". the description of "ungoogled" on this website is:

> Chromium without Google integration and enhanced privacy, based on the "ungoogled-chromium" project of Eloston. 

it seems that it's just compiled by someone else, and released on this website, but why wouldn't it be released here?

also, it seems to also have widevine support built-in. 

all the binaries are hosted here: https://github.com/macchrome/macstable/releases.

there are also windows versions, which have the description:

> Standard build of Eloston's ungoogled-chromium. All patches applied, apart from "Safe Browser". Linking failed due to safe browsing being removed, so I decided not to remove any element of safe browsing.

the github link for the windows version is here: https://github.com/macchrome/winchrome/releases.

the windows version also includes widevine. 

my question(s) are, are these builds legitimate, can i trust them, and why aren't they submitted here to this repository?

thanks for this great project, by the way - i switched from regular chromium about a month ago and it's been a great transition. i appreciate the work y'all put in to this project!

**Comment by Eloston** [comment]
Those Windows builds aren't downloadable here because they aren't produced from the source code present in ungoogled-software/ungoogled-chromium-windows. In fact, no binaries can be built right now; help is needed in https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/2

> my question(s) are, are these builds legitimate, can i trust them, and why aren't they submitted here to this repository?

I don't know much about those binaries so I cannot say. Sorry.
