### ISSUE TITLE
Please Update!

### ISSUE THREAD

**Issue by v00v** [ungoogled-software/ungoogled-chromium-binaries#81]
Please keep this binary packages up to date, otherwise what is the point of https://ungoogled-software.github.io/ungoogled-chromium-binaries/

Newest Ungoogled Chromium Release For Arch Linux Is v75.0.3770.100-1.
and your binary packages website there is still v74.0.3729.136-1 (DEV)

Thank you!

**Comment by kramred** [comment]
Hello! 
This is a project run by volunteers and I'm thankful that it exists and is being maintained.

The readme for this repository states in the first two paragraphs (bold part also on the website):

> Website for ungoogled-chromium contributor-submitted binaries

> **IMPORTANT: These binaries are provided by anyone who are willing to build and submit them. Because these binaries are not necessarily reproducible, authenticity cannot be guaranteed.**

The point of https://ungoogled-software.github.io/ungoogled-chromium-binaries/ is to make binaries that are built by volunteers/contributors available to everyone who is willing to trust these people.

Building the binary requires resources (i.e. time & money) – the maintainer may not build for Arch Linux or may not want to share their binary.

You could check who built previous releases for [Arch Linux](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/archlinux/) and ask them nicely or offer resources that they may need (money to rent a build system?). Or you can invest time and follow the instructions for building the binaries yourself and maybe share them via pull request to be made available on the [binaries web-site](https://ungoogled-software.github.io/ungoogled-chromium-binaries/). Or maybe use the portable linux version?

Anyway, I hope that's cleared things up a little bit.
